# Generated by Django 4.2.7 on 2023-11-13 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
        migrations.AddField(
            model_name="ad",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор объявления",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата и время создания объявления",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание товара"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="ads/", verbose_name="Фото товара"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Цена товара"
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="title",
            field=models.CharField(
                default="", max_length=200, verbose_name="Название товара"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="ad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ads.ad",
                verbose_name="Объявление, где оставлен отзыв",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор отзыва",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата и время создания отзыва",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="text",
            field=models.TextField(default="", verbose_name="Текст отзыва"),
        ),
    ]
