# Generated by Django 3.2.6 on 2023-12-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='фамилия')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='электронная почта')),
                ('password', models.CharField(max_length=100, verbose_name='пароль')),
                ('phone', models.CharField(max_length=50, unique=True, verbose_name='номер телефона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user', verbose_name='аватар')),
                ('role', models.CharField(choices=[('user', 'юзер'), ('admin', 'админ')], default=('user', 'юзер'), max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
